---
- hosts: all
  become: true
  remote_user: root
  gather_facts: ture
  tasks:
  - name: copy files
    copy: 
     src: /root/playbook/pb4.yaml
     dest: /opt/
  - name: file create
    file: name=sample mode=755 user=root state:present
    
  - name: display message
    debug:
     msg: files are copied
